VARIABLES:
  dz: [0.001, 0.5]  # thickness of each vertical layer (unit : m)
  layer_type: [0, 0]  # Fresnel layers (set all to 0 if toon : True)
  cdom: [1, 0]  # Only for layer type :: 1
  rho: [850, 850]  # density of each layer (unit : kg m-3)
  rf: 1
  shp: [0, 0]  # grain shape (He et al. 2016, 2017)
  rds: [1000, 1000]  # effective grain or bubble radius
  water: [0, 0]  # radius of optional liquid water coating
  hex_side: [10000, 10000]
  hex_length: [10000, 10000]
  shp_fctr: [0, 0]
  ar: [0, 0]

