impurities:
  algae:
    name: "algae"
    file: "Cook2020_glacier_algae_4_40.nc"
    cfactor: 20
    coated: False
    unit: 1
    conc: [0,0]
  dust:
    name: "dust"
    file: "dust_skiles_size1.nc"
    cfactor: 1
    coated: False
    unit: 0
    conc: [1000,0]