
CTRL:
  WRITE_CONFIG_TO_TEXTFILE: False
  verbosity: 0
  SHOW_FIGS: True
  SAVE_FIGS: False
  PRINT_BBA: True
  PRINT_BAND_RATIOS: True
  SMOOTH: False
  WINDOW_SIZE: 9
  POLY_ORDER: 3
  VIS_MAX_IDX: 39
  NIR_MAX_IDX: 480

PATHS:
  DIR_BASE: "/home/joe/Code/BioSNICAR_GO_PY/"
  WVL: "/home/joe/Code/BioSNICAR_GO_PY/Data/OP_data/wavelengths.csv"
  SPHERE_ICE:  "Data/OP_data/480band/ice_spherical_grains/"
  HEX_ICE: "Data/OP_data/480band/ice_hexagonal_columns/"
  BUBBLY_ICE: "Data/OP_data/480band/bubbly_ice_files/"
  RI_ICE: "Data/OP_data/480band/"
  OP_DIR_STUBS: ["ice_Wrn84/ice_Wrn84_", "ice_Wrn08/ice_Wrn08_", "ice_Pic16/ice_Pic16_"]
  SFC: "/Data/OP_data/480band/r_sfc/blue_ice_spectrum_s10290721.csv"
  FN_ICE: "/Data/OP_data/480band/rfidx_ice.nc"
  FN_WATER: "/Data/OP_data/Refractive_Index_Liquid_Water_Segelstein_1981.csv"